### ISSUE TITLE
DataTable warning in search bar

### ISSUE THREAD

**Issue by JerrickTram** [MarijaStanojcic/RDatasets#1]
The issue isn't that frequent although whenever I were to type in the search bar, the DataTable warning would pop up and disconnect the Shiny server 
![R Datasets Warning](https://user-images.githubusercontent.com/43930210/56168823-4b111300-5faa-11e9-8660-b07f4fd976cd.png)

**Comment by MarijaStanojcic** [comment]
Hi Jerrick, thank for letting me know. I change memory settings in R shiny and it seems to be working now, at least for me. Can you check again and let me know if you are still encountering the same problem?

**Comment by JerrickTram** [comment]
No issues. Thanks Marija!
